// Powered by OnSpace.AI
export interface AppTemplate {
  id: string;
  name: string;
  urduName: string;
  description: string;
  urduDescription: string;
  icon: string;
  color: string;
  files: TemplateFile[];
  tags: string[];
  category: string;
  isReady?: boolean; // ready-to-install
}

export interface TemplateFile {
  path: string;
  description: string;
  type: 'component' | 'screen' | 'config' | 'data' | 'util' | 'service' | 'hook' | 'context';
}

export const TEMPLATE_CATEGORIES = [
  { id: 'سب', label: 'سب', icon: 'apps' },
  { id: 'پسندیدہ', label: 'پسندیدہ', icon: 'favorite' },
  { id: 'ڈیولپر', label: 'ڈیولپر', icon: 'code' },
  { id: 'میڈیا', label: 'میڈیا', icon: 'photo-library' },
  { id: 'پروڈکٹیویٹی', label: 'پروڈکٹیویٹی', icon: 'task-alt' },
  { id: 'سوشل', label: 'سوشل', icon: 'chat' },
  { id: 'کاروبار', label: 'کاروبار', icon: 'store' },
  { id: 'صحت', label: 'صحت', icon: 'favorite-border' },
  { id: 'تعلیم', label: 'تعلیم', icon: 'school' },
  { id: 'مالیات', label: 'مالیات', icon: 'account-balance' },
  { id: 'سفر', label: 'سفر', icon: 'flight' },
  { id: 'ڈیش بورڈ', label: 'ڈیش بورڈ', icon: 'dashboard' },
  { id: 'یوٹیلیٹی', label: 'یوٹیلیٹی', icon: 'build' },
  { id: 'گیمز', label: 'گیمز', icon: 'sports-esports' },
  { id: 'فیملی', label: 'فیملی', icon: 'family-restroom' },
];

export const TEMPLATES: AppTemplate[] = [

  // ━━━━━━━━━━ ڈیولپر ━━━━━━━━━━
  {
    id: 'github-client',
    name: 'GitHub Client App',
    urduName: 'GitHub کلائنٹ',
    description: 'Full GitHub client with repos, issues, PRs, code viewer and notifications',
    urduDescription: 'ریپوز، ایشوز، PRs، کوڈ ویوئر اور نوٹیفکیشنز کے ساتھ مکمل GitHub کلائنٹ',
    icon: 'code',
    color: '#f0f6fc',
    category: 'ڈیولپر',
    isReady: true,
    tags: ['GitHub', 'OAuth', 'API', 'Code'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'فیڈ اسکرین', type: 'screen' },
      { path: 'screens/ReposScreen.js', description: 'ریپوزیٹریز', type: 'screen' },
      { path: 'screens/RepoDetailScreen.js', description: 'ریپو ڈیٹیل', type: 'screen' },
      { path: 'screens/IssuesScreen.js', description: 'ایشوز', type: 'screen' },
      { path: 'screens/PullRequestsScreen.js', description: 'Pull Requests', type: 'screen' },
      { path: 'screens/CodeViewerScreen.js', description: 'کوڈ ویوئر', type: 'screen' },
      { path: 'screens/NotificationsScreen.js', description: 'نوٹیفکیشنز', type: 'screen' },
      { path: 'screens/ProfileScreen.js', description: 'پروفائل', type: 'screen' },
      { path: 'components/RepoCard.js', description: 'ریپو کارڈ', type: 'component' },
      { path: 'components/IssueItem.js', description: 'ایشو آئٹم', type: 'component' },
      { path: 'components/PRItem.js', description: 'PR آئٹم', type: 'component' },
      { path: 'components/CodeHighlight.js', description: 'کوڈ ہائی لائٹ', type: 'component' },
      { path: 'components/LanguageBar.js', description: 'زبان بار', type: 'component' },
      { path: 'services/githubAPI.js', description: 'GitHub API سروس', type: 'service' },
      { path: 'services/authService.js', description: 'GitHub OAuth', type: 'service' },
      { path: 'contexts/AuthContext.js', description: 'auth کانٹیکسٹ', type: 'context' },
      { path: 'contexts/ReposContext.js', description: 'ریپوز کانٹیکسٹ', type: 'context' },
      { path: 'hooks/useGitHub.js', description: 'GitHub ہک', type: 'hook' },
      { path: 'utils/formatDate.js', description: 'تاریخ فارمیٹ', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
      { path: 'app.json', description: 'Expo config', type: 'config' },
    ],
  },
  {
    id: 'expo-go-showcase',
    name: 'Expo Go Showcase App',
    urduName: 'Expo Go شوکیس',
    description: 'Expo Go compatible app with all Expo APIs demo: Camera, Location, Haptics, etc.',
    urduDescription: 'تمام Expo APIs کا مظاہرہ — Camera، Location، Haptics اور مزید',
    icon: 'smartphone',
    color: '#4630EB',
    category: 'ڈیولپر',
    isReady: true,
    tags: ['Expo', 'APIs', 'Demo', 'Camera'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'APIs لسٹ', type: 'screen' },
      { path: 'screens/CameraScreen.js', description: 'Camera API', type: 'screen' },
      { path: 'screens/LocationScreen.js', description: 'Location API', type: 'screen' },
      { path: 'screens/HapticsScreen.js', description: 'Haptics API', type: 'screen' },
      { path: 'screens/NotificationsScreen.js', description: 'Notifications API', type: 'screen' },
      { path: 'screens/FileSystemScreen.js', description: 'FileSystem API', type: 'screen' },
      { path: 'screens/ClipboardScreen.js', description: 'Clipboard API', type: 'screen' },
      { path: 'screens/SensorsScreen.js', description: 'Sensors API', type: 'screen' },
      { path: 'components/ApiCard.js', description: 'API کارڈ', type: 'component' },
      { path: 'components/DemoResult.js', description: 'ڈیمو نتیجہ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
      { path: 'app.json', description: 'Expo config', type: 'config' },
    ],
  },
  {
    id: 'wordpress-app',
    name: 'WordPress Mobile App',
    urduName: 'WordPress ایپ',
    description: 'Connect to WordPress REST API — posts, pages, categories, comments, media',
    urduDescription: 'WordPress REST API سے جوڑیں — پوسٹس، صفحات، کیٹیگریز، تبصرے، میڈیا',
    icon: 'web',
    color: '#21759b',
    category: 'ڈیولپر',
    isReady: true,
    tags: ['WordPress', 'REST API', 'CMS', 'Blog'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/PostsScreen.js', description: 'پوسٹس', type: 'screen' },
      { path: 'screens/PostDetailScreen.js', description: 'پوسٹ ڈیٹیل', type: 'screen' },
      { path: 'screens/PagesScreen.js', description: 'صفحات', type: 'screen' },
      { path: 'screens/CategoriesScreen.js', description: 'کیٹیگریز', type: 'screen' },
      { path: 'screens/CommentsScreen.js', description: 'تبصرے', type: 'screen' },
      { path: 'screens/MediaScreen.js', description: 'میڈیا لائبریری', type: 'screen' },
      { path: 'screens/LoginScreen.js', description: 'لاگ ان (JWT)', type: 'screen' },
      { path: 'components/PostCard.js', description: 'پوسٹ کارڈ', type: 'component' },
      { path: 'components/HtmlRenderer.js', description: 'HTML رینڈرر', type: 'component' },
      { path: 'components/CommentItem.js', description: 'تبصرہ آئٹم', type: 'component' },
      { path: 'services/wpAPI.js', description: 'WordPress REST API', type: 'service' },
      { path: 'services/authService.js', description: 'JWT Auth', type: 'service' },
      { path: 'contexts/WordPressContext.js', description: 'WP کانٹیکسٹ', type: 'context' },
      { path: 'config/wordpress.js', description: 'WP سائٹ URL کنفیگ', type: 'config' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'netlify-dashboard',
    name: 'Netlify Dashboard App',
    urduName: 'Netlify ڈیش بورڈ',
    description: 'Manage Netlify sites, deploys, builds, env vars and analytics',
    urduDescription: 'Netlify سائٹس، ڈیپلوز، بلڈز، env vars اور اینالٹکس کا انتظام',
    icon: 'cloud',
    color: '#00c7b7',
    category: 'ڈیولپر',
    isReady: true,
    tags: ['Netlify', 'Deploy', 'CI/CD', 'Dashboard'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/SitesScreen.js', description: 'سائٹس', type: 'screen' },
      { path: 'screens/SiteDetailScreen.js', description: 'سائٹ ڈیٹیل', type: 'screen' },
      { path: 'screens/DeploysScreen.js', description: 'ڈیپلوز', type: 'screen' },
      { path: 'screens/DeployLogScreen.js', description: 'ڈیپلو لاگ', type: 'screen' },
      { path: 'screens/EnvVarsScreen.js', description: 'Environment Variables', type: 'screen' },
      { path: 'screens/FormsScreen.js', description: 'Netlify Forms', type: 'screen' },
      { path: 'screens/FunctionsScreen.js', description: 'Serverless Functions', type: 'screen' },
      { path: 'components/SiteCard.js', description: 'سائٹ کارڈ', type: 'component' },
      { path: 'components/DeployItem.js', description: 'ڈیپلو آئٹم', type: 'component' },
      { path: 'components/StatusBadge.js', description: 'اسٹیٹس بیج', type: 'component' },
      { path: 'services/netlifyAPI.js', description: 'Netlify API', type: 'service' },
      { path: 'services/authService.js', description: 'Netlify Auth', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'vercel-dashboard',
    name: 'Vercel Dashboard App',
    urduName: 'Vercel ڈیش بورڈ',
    description: 'Manage Vercel projects, deployments, domains and analytics from mobile',
    urduDescription: 'Vercel پروجیکٹس، ڈیپلوئمنٹس، ڈومینز اور اینالٹکس موبائل سے',
    icon: 'cloud-upload',
    color: '#ffffff',
    category: 'ڈیولپر',
    isReady: true,
    tags: ['Vercel', 'Deploy', 'Serverless'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ProjectsScreen.js', description: 'پروجیکٹس', type: 'screen' },
      { path: 'screens/DeploymentsScreen.js', description: 'ڈیپلوئمنٹس', type: 'screen' },
      { path: 'screens/DomainsScreen.js', description: 'ڈومینز', type: 'screen' },
      { path: 'screens/AnalyticsScreen.js', description: 'اینالٹکس', type: 'screen' },
      { path: 'components/ProjectCard.js', description: 'پروجیکٹ کارڈ', type: 'component' },
      { path: 'components/DeployStatus.js', description: 'ڈیپلو اسٹیٹس', type: 'component' },
      { path: 'services/vercelAPI.js', description: 'Vercel API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'api-tester',
    name: 'API Tester App',
    urduName: 'API ٹیسٹر',
    description: 'Postman-like API tester with GET/POST/PUT/DELETE, headers and auth',
    urduDescription: 'GET/POST/PUT/DELETE، ہیڈرز اور auth کے ساتھ Postman جیسا API ٹیسٹر',
    icon: 'network-check',
    color: '#ff6c37',
    category: 'ڈیولپر',
    tags: ['API', 'HTTP', 'REST', 'Testing'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/RequestScreen.js', description: 'درخواست', type: 'screen' },
      { path: 'screens/HistoryScreen.js', description: 'ہسٹری', type: 'screen' },
      { path: 'screens/CollectionsScreen.js', description: 'کلیکشنز', type: 'screen' },
      { path: 'components/MethodPicker.js', description: 'HTTP طریقہ', type: 'component' },
      { path: 'components/ResponseViewer.js', description: 'جواب ویوئر', type: 'component' },
      { path: 'components/HeadersEditor.js', description: 'ہیڈرز ایڈیٹر', type: 'component' },
      { path: 'utils/httpClient.js', description: 'HTTP کلائنٹ', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'code-editor',
    name: 'Code Editor App',
    urduName: 'کوڈ ایڈیٹر',
    description: 'Mobile code editor with syntax highlighting, themes and file management',
    urduDescription: 'سینٹیکس ہائی لائٹنگ، تھیمز اور فائل مینجمنٹ کے ساتھ موبائل کوڈ ایڈیٹر',
    icon: 'code',
    color: '#007acc',
    category: 'ڈیولپر',
    tags: ['Editor', 'Code', 'Syntax'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/EditorScreen.js', description: 'ایڈیٹر', type: 'screen' },
      { path: 'screens/FilesScreen.js', description: 'فائلز', type: 'screen' },
      { path: 'screens/SettingsScreen.js', description: 'سیٹنگز', type: 'screen' },
      { path: 'components/CodeArea.js', description: 'کوڈ ایریا', type: 'component' },
      { path: 'components/TokenHighlighter.js', description: 'ٹوکن ہائی لائٹر', type: 'component' },
      { path: 'components/FileTree.js', description: 'فائل ٹری', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'git-dashboard',
    name: 'Git Dashboard App',
    urduName: 'Git ڈیش بورڈ',
    description: 'Git visualization with commits, branches, diffs and team activity',
    urduDescription: 'کمٹس، برانچز، ڈفز اور ٹیم ایکٹیویٹی کے ساتھ Git ویژولائزیشن',
    icon: 'merge-type',
    color: '#f05032',
    category: 'ڈیولپر',
    tags: ['Git', 'Commits', 'Branches'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CommitsScreen.js', description: 'کمٹس', type: 'screen' },
      { path: 'screens/BranchesScreen.js', description: 'برانچز', type: 'screen' },
      { path: 'screens/DiffScreen.js', description: 'ڈف ویوئر', type: 'screen' },
      { path: 'components/CommitItem.js', description: 'کمٹ آئٹم', type: 'component' },
      { path: 'components/BranchItem.js', description: 'برانچ آئٹم', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'npm-explorer',
    name: 'NPM Package Explorer',
    urduName: 'NPM ایکسپلورر',
    description: 'Browse NPM packages, view docs, changelogs, dependencies and stats',
    urduDescription: 'NPM پیکیجز براؤز کریں، دستاویزات، changelogs، dependencies اور stats',
    icon: 'inventory',
    color: '#cb3837',
    category: 'ڈیولپر',
    tags: ['NPM', 'Packages', 'Search'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/SearchScreen.js', description: 'سرچ', type: 'screen' },
      { path: 'screens/PackageDetailScreen.js', description: 'پیکیج ڈیٹیل', type: 'screen' },
      { path: 'screens/TrendingScreen.js', description: 'مشہور پیکیجز', type: 'screen' },
      { path: 'components/PackageCard.js', description: 'پیکیج کارڈ', type: 'component' },
      { path: 'services/npmAPI.js', description: 'NPM API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'ci-cd-monitor',
    name: 'CI/CD Monitor App',
    urduName: 'CI/CD مانیٹر',
    description: 'Monitor CI/CD pipelines from GitHub Actions, Jenkins and CircleCI',
    urduDescription: 'GitHub Actions، Jenkins اور CircleCI سے CI/CD پائپ لائنز مانیٹر',
    icon: 'loop',
    color: '#2088ff',
    category: 'ڈیولپر',
    tags: ['CI/CD', 'Pipelines', 'Monitor'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/PipelinesScreen.js', description: 'پائپ لائنز', type: 'screen' },
      { path: 'screens/BuildDetailScreen.js', description: 'بلڈ ڈیٹیل', type: 'screen' },
      { path: 'screens/LogsScreen.js', description: 'لاگز', type: 'screen' },
      { path: 'components/PipelineCard.js', description: 'پائپ لائن کارڈ', type: 'component' },
      { path: 'components/BuildStatus.js', description: 'بلڈ اسٹیٹس', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ میڈیا ━━━━━━━━━━
  {
    id: 'gallery-app',
    name: 'Gallery App',
    urduName: 'گیلری ایپ',
    description: 'A beautiful photo gallery with grid layout and full-screen viewer',
    urduDescription: 'گرڈ لے آؤٹ اور فل اسکرین ویوئر کے ساتھ خوبصورت فوٹو گیلری',
    icon: 'photo-library',
    color: '#ff6b6b',
    category: 'میڈیا',
    isReady: true,
    tags: ['Images', 'FlatList', 'Navigation'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم اسکرین', type: 'screen' },
      { path: 'screens/GalleryScreen.js', description: 'گیلری اسکرین', type: 'screen' },
      { path: 'screens/FullImageScreen.js', description: 'فل اسکرین ویوئر', type: 'screen' },
      { path: 'components/ImageCard.js', description: 'تصویر کارڈ', type: 'component' },
      { path: 'components/ImageGrid.js', description: 'گرڈ لے آؤٹ', type: 'component' },
      { path: 'navigation/AppNavigator.js', description: 'نیویگیشن', type: 'component' },
      { path: 'data/images.js', description: 'تصاویر ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'video-player',
    name: 'Video Player App',
    urduName: 'ویڈیو پلیئر',
    description: 'Full-featured video player with playlist, controls and fullscreen',
    urduDescription: 'پلے لسٹ، کنٹرولز اور فل اسکرین کے ساتھ ویڈیو پلیئر',
    icon: 'play-circle-filled',
    color: '#ff4757',
    category: 'میڈیا',
    tags: ['Video', 'expo-video', 'Playlist'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/PlayerScreen.js', description: 'پلیئر اسکرین', type: 'screen' },
      { path: 'screens/PlaylistScreen.js', description: 'پلے لسٹ', type: 'screen' },
      { path: 'components/VideoControls.js', description: 'ویڈیو کنٹرولز', type: 'component' },
      { path: 'components/VideoCard.js', description: 'ویڈیو کارڈ', type: 'component' },
      { path: 'hooks/useVideoPlayer.js', description: 'پلیئر ہک', type: 'hook' },
      { path: 'data/videos.js', description: 'ویڈیو ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'music-player',
    name: 'Music Player App',
    urduName: 'میوزک پلیئر',
    description: 'Beautiful music player with album art, queue and audio controls',
    urduDescription: 'البم آرٹ، قطار اور آڈیو کنٹرولز کے ساتھ خوبصورت میوزک پلیئر',
    icon: 'music-note',
    color: '#a29bfe',
    category: 'میڈیا',
    tags: ['Audio', 'expo-av', 'Queue'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/NowPlayingScreen.js', description: 'ابھی چل رہا ہے', type: 'screen' },
      { path: 'screens/LibraryScreen.js', description: 'لائبریری', type: 'screen' },
      { path: 'screens/AlbumScreen.js', description: 'البم', type: 'screen' },
      { path: 'components/MiniPlayer.js', description: 'منی پلیئر', type: 'component' },
      { path: 'components/TrackItem.js', description: 'ٹریک آئٹم', type: 'component' },
      { path: 'hooks/useAudioPlayer.js', description: 'آڈیو ہک', type: 'hook' },
      { path: 'data/tracks.js', description: 'ٹریکس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'podcast-app',
    name: 'Podcast App',
    urduName: 'پوڈکاسٹ ایپ',
    description: 'Podcast player with episode list, progress tracking and subscriptions',
    urduDescription: 'ایپی سوڈ لسٹ، پروگریس ٹریکنگ اور سبسکرپشنز کے ساتھ پوڈکاسٹ پلیئر',
    icon: 'podcasts',
    color: '#fd79a8',
    category: 'میڈیا',
    tags: ['Audio', 'Podcast', 'Streaming'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/EpisodeScreen.js', description: 'ایپی سوڈ', type: 'screen' },
      { path: 'screens/SubscriptionsScreen.js', description: 'سبسکرپشنز', type: 'screen' },
      { path: 'components/EpisodeCard.js', description: 'ایپی سوڈ کارڈ', type: 'component' },
      { path: 'components/PlayerBar.js', description: 'پلیئر بار', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'stories-app',
    name: 'Stories App',
    urduName: 'اسٹوریز ایپ',
    description: 'Instagram-like stories with auto-advance, progress bars and reactions',
    urduDescription: 'آٹو ایڈوانس، پروگریس بارز اور ری ایکشنز کے ساتھ اسٹوریز',
    icon: 'auto-stories',
    color: '#e17055',
    category: 'میڈیا',
    tags: ['Stories', 'Animation', 'Media'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/StoriesScreen.js', description: 'اسٹوریز اسکرین', type: 'screen' },
      { path: 'components/StoryViewer.js', description: 'اسٹوری ویوئر', type: 'component' },
      { path: 'components/ProgressBar.js', description: 'پروگریس بار', type: 'component' },
      { path: 'components/StoryCircle.js', description: 'اسٹوری سرکل', type: 'component' },
      { path: 'data/stories.js', description: 'اسٹوریز ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'photo-editor',
    name: 'Photo Editor App',
    urduName: 'فوٹو ایڈیٹر',
    description: 'Photo editing with filters, crop, brightness and contrast controls',
    urduDescription: 'فلٹرز، کراپ، برائٹنس اور کنٹراسٹ کنٹرولز کے ساتھ فوٹو ایڈیٹر',
    icon: 'photo-filter',
    color: '#00b894',
    category: 'میڈیا',
    tags: ['Image', 'Filters', 'Editing'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/EditorScreen.js', description: 'ایڈیٹر', type: 'screen' },
      { path: 'components/FilterStrip.js', description: 'فلٹر پٹی', type: 'component' },
      { path: 'components/AdjustSliders.js', description: 'ایڈجسٹ سلائیڈرز', type: 'component' },
      { path: 'components/ToolBar.js', description: 'ٹول بار', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ پروڈکٹیویٹی ━━━━━━━━━━
  {
    id: 'notes-app',
    name: 'Notes App',
    urduName: 'نوٹس ایپ',
    description: 'Rich notes with categories, search, markdown support and color coding',
    urduDescription: 'کیٹیگریز، سرچ، مارک ڈاؤن سپورٹ اور رنگ کوڈنگ کے ساتھ نوٹس',
    icon: 'note',
    color: '#ffd700',
    category: 'پروڈکٹیویٹی',
    isReady: true,
    tags: ['AsyncStorage', 'Search', 'CRUD'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/NotesListScreen.js', description: 'نوٹس لسٹ', type: 'screen' },
      { path: 'screens/NoteDetailScreen.js', description: 'نوٹ ڈیٹیل', type: 'screen' },
      { path: 'screens/EditNoteScreen.js', description: 'نوٹ ایڈٹ', type: 'screen' },
      { path: 'components/NoteCard.js', description: 'نوٹ کارڈ', type: 'component' },
      { path: 'components/SearchBar.js', description: 'سرچ بار', type: 'component' },
      { path: 'contexts/NotesContext.js', description: 'نوٹس کانٹیکسٹ', type: 'context' },
      { path: 'hooks/useNotes.js', description: 'نوٹس ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'todo-app',
    name: 'Todo App',
    urduName: 'ٹوڈو ایپ',
    description: 'Task manager with priorities, due dates, categories and completion tracking',
    urduDescription: 'ترجیحات، آخری تاریخ، کیٹیگریز اور مکمل ٹریکنگ کے ساتھ ٹاسک مینیجر',
    icon: 'check-circle',
    color: '#55efc4',
    category: 'پروڈکٹیویٹی',
    isReady: true,
    tags: ['Tasks', 'Storage', 'Swipe'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/TodoListScreen.js', description: 'ٹوڈو لسٹ', type: 'screen' },
      { path: 'screens/AddTodoScreen.js', description: 'ٹوڈو شامل', type: 'screen' },
      { path: 'components/TodoItem.js', description: 'ٹوڈو آئٹم', type: 'component' },
      { path: 'components/FilterTabs.js', description: 'فلٹر ٹیبز', type: 'component' },
      { path: 'contexts/TodoContext.js', description: 'ٹوڈو کانٹیکسٹ', type: 'context' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'calendar-app',
    name: 'Calendar App',
    urduName: 'کیلنڈر ایپ',
    description: 'Monthly calendar with events, reminders and agenda view',
    urduDescription: 'ایونٹس، ریمائنڈرز اور ایجنڈا ویو کے ساتھ ماہانہ کیلنڈر',
    icon: 'calendar-today',
    color: '#74b9ff',
    category: 'پروڈکٹیویٹی',
    tags: ['Calendar', 'Events', 'Dates'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CalendarScreen.js', description: 'کیلنڈر', type: 'screen' },
      { path: 'screens/EventDetailScreen.js', description: 'ایونٹ ڈیٹیل', type: 'screen' },
      { path: 'screens/AddEventScreen.js', description: 'ایونٹ شامل', type: 'screen' },
      { path: 'components/CalendarGrid.js', description: 'کیلنڈر گرڈ', type: 'component' },
      { path: 'components/EventList.js', description: 'ایونٹ لسٹ', type: 'component' },
      { path: 'data/events.js', description: 'ایونٹس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker App',
    urduName: 'عادات ٹریکر',
    description: 'Build habits with streaks, reminders, progress charts and achievements',
    urduDescription: 'اسٹریکس، ریمائنڈرز، پروگریس چارٹس اور اچیومنٹس کے ساتھ عادات',
    icon: 'trending-up',
    color: '#fd79a8',
    category: 'پروڈکٹیویٹی',
    tags: ['Habits', 'Streaks', 'Charts'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HabitsScreen.js', description: 'عادات', type: 'screen' },
      { path: 'screens/HabitDetailScreen.js', description: 'عادت ڈیٹیل', type: 'screen' },
      { path: 'screens/StatsScreen.js', description: 'اسٹیٹس', type: 'screen' },
      { path: 'components/HabitCard.js', description: 'عادت کارڈ', type: 'component' },
      { path: 'components/StreakBadge.js', description: 'اسٹریک بیج', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'timer-app',
    name: 'Timer & Stopwatch',
    urduName: 'ٹائمر ایپ',
    description: 'Countdown timer, stopwatch with laps and Pomodoro technique support',
    urduDescription: 'کاؤنٹ ڈاؤن ٹائمر، لیپس کے ساتھ اسٹاپ واچ اور پومودورو تکنیک',
    icon: 'timer',
    color: '#e17055',
    category: 'پروڈکٹیویٹی',
    tags: ['Timer', 'Stopwatch', 'Pomodoro'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/TimerScreen.js', description: 'ٹائمر', type: 'screen' },
      { path: 'screens/StopwatchScreen.js', description: 'اسٹاپ واچ', type: 'screen' },
      { path: 'screens/PomodoroScreen.js', description: 'پومودورو', type: 'screen' },
      { path: 'components/CircularTimer.js', description: 'سرکلر ٹائمر', type: 'component' },
      { path: 'components/LapList.js', description: 'لیپ لسٹ', type: 'component' },
      { path: 'hooks/useTimer.js', description: 'ٹائمر ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'calculator-app',
    name: 'Calculator App',
    urduName: 'کیلکولیٹر',
    description: 'Scientific calculator with history, unit converter and formula support',
    urduDescription: 'ہسٹری، یونٹ کنورٹر اور فارمولا سپورٹ کے ساتھ سائنٹفک کیلکولیٹر',
    icon: 'calculate',
    color: '#6c5ce7',
    category: 'پروڈکٹیویٹی',
    isReady: true,
    tags: ['Calculator', 'Math', 'Scientific'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CalculatorScreen.js', description: 'کیلکولیٹر', type: 'screen' },
      { path: 'components/KeyPad.js', description: 'کی پیڈ', type: 'component' },
      { path: 'components/Display.js', description: 'ڈسپلے', type: 'component' },
      { path: 'utils/mathEngine.js', description: 'ریاضی انجن', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'password-manager',
    name: 'Password Manager',
    urduName: 'پاسورڈ مینیجر',
    description: 'Secure password manager with categories, generator and biometric lock',
    urduDescription: 'کیٹیگریز، جنریٹر اور بائیومیٹرک لاک کے ساتھ محفوظ پاسورڈ مینیجر',
    icon: 'lock',
    color: '#00cec9',
    category: 'پروڈکٹیویٹی',
    tags: ['Security', 'Encryption', 'Biometric'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/VaultScreen.js', description: 'والٹ', type: 'screen' },
      { path: 'screens/AddPasswordScreen.js', description: 'پاسورڈ شامل', type: 'screen' },
      { path: 'screens/GeneratorScreen.js', description: 'جنریٹر', type: 'screen' },
      { path: 'components/PasswordCard.js', description: 'پاسورڈ کارڈ', type: 'component' },
      { path: 'utils/encryption.js', description: 'انکرپشن', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ سوشل ━━━━━━━━━━
  {
    id: 'chat-app',
    name: 'Chat App',
    urduName: 'چیٹ ایپ',
    description: 'Real-time chat with message bubbles, media sharing and read receipts',
    urduDescription: 'میسج ببلز، میڈیا شیئرنگ اور ریڈ ریسیپٹس کے ساتھ ریئل ٹائم چیٹ',
    icon: 'chat',
    color: '#00cec9',
    category: 'سوشل',
    isReady: true,
    tags: ['Chat', 'Realtime', 'Messages'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ChatListScreen.js', description: 'چیٹ لسٹ', type: 'screen' },
      { path: 'screens/ChatScreen.js', description: 'چیٹ اسکرین', type: 'screen' },
      { path: 'screens/ProfileScreen.js', description: 'پروفائل', type: 'screen' },
      { path: 'components/MessageBubble.js', description: 'میسج ببل', type: 'component' },
      { path: 'components/ChatListItem.js', description: 'چیٹ لسٹ آئٹم', type: 'component' },
      { path: 'components/MessageInput.js', description: 'میسج ان پٹ', type: 'component' },
      { path: 'contexts/ChatContext.js', description: 'چیٹ کانٹیکسٹ', type: 'context' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'social-feed',
    name: 'Social Feed App',
    urduName: 'سوشل فیڈ',
    description: 'Instagram-like social feed with posts, likes, comments and stories',
    urduDescription: 'پوسٹس، لائکس، کمنٹس اور اسٹوریز کے ساتھ سوشل فیڈ',
    icon: 'dynamic-feed',
    color: '#e84393',
    category: 'سوشل',
    tags: ['Feed', 'Social', 'Posts'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/FeedScreen.js', description: 'فیڈ', type: 'screen' },
      { path: 'screens/ProfileScreen.js', description: 'پروفائل', type: 'screen' },
      { path: 'screens/PostDetailScreen.js', description: 'پوسٹ ڈیٹیل', type: 'screen' },
      { path: 'components/PostCard.js', description: 'پوسٹ کارڈ', type: 'component' },
      { path: 'components/StoriesRow.js', description: 'اسٹوریز رو', type: 'component' },
      { path: 'data/posts.js', description: 'پوسٹس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'contact-book',
    name: 'Contact Book App',
    urduName: 'رابطہ کتاب',
    description: 'Contact manager with groups, search, call/message integration',
    urduDescription: 'گروپس، سرچ، کال/میسج انٹیگریشن کے ساتھ کانٹیکٹ مینیجر',
    icon: 'contacts',
    color: '#0984e3',
    category: 'سوشل',
    tags: ['Contacts', 'Groups', 'Search'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ContactsScreen.js', description: 'کانٹیکٹس', type: 'screen' },
      { path: 'screens/ContactDetailScreen.js', description: 'ڈیٹیل', type: 'screen' },
      { path: 'screens/AddContactScreen.js', description: 'کانٹیکٹ شامل', type: 'screen' },
      { path: 'components/ContactItem.js', description: 'کانٹیکٹ آئٹم', type: 'component' },
      { path: 'components/Avatar.js', description: 'اوتار', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'dating-app',
    name: 'Dating App UI',
    urduName: 'ڈیٹنگ ایپ UI',
    description: 'Swipe-based dating app with profiles, matches, chat and filters',
    urduDescription: 'پروفائلز، میچز، چیٹ اور فلٹرز کے ساتھ سوائپ بیسڈ ڈیٹنگ ایپ',
    icon: 'favorite',
    color: '#e84393',
    category: 'سوشل',
    tags: ['Swipe', 'Matches', 'Profiles'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DiscoverScreen.js', description: 'دریافت', type: 'screen' },
      { path: 'screens/MatchesScreen.js', description: 'میچز', type: 'screen' },
      { path: 'screens/ProfileScreen.js', description: 'پروفائل', type: 'screen' },
      { path: 'components/SwipeCard.js', description: 'سوائپ کارڈ', type: 'component' },
      { path: 'components/MatchItem.js', description: 'میچ آئٹم', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'forum-app',
    name: 'Forum App',
    urduName: 'فورم ایپ',
    description: 'Community forum with categories, threads, upvotes and replies',
    urduDescription: 'کیٹیگریز، تھریڈز، اپ ووٹس اور ریپلائز کے ساتھ کمیونٹی فورم',
    icon: 'forum',
    color: '#b2bec3',
    category: 'سوشل',
    tags: ['Forum', 'Threads', 'Community'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ForumHomeScreen.js', description: 'فورم ہوم', type: 'screen' },
      { path: 'screens/ThreadScreen.js', description: 'تھریڈ', type: 'screen' },
      { path: 'components/ThreadCard.js', description: 'تھریڈ کارڈ', type: 'component' },
      { path: 'components/ReplyItem.js', description: 'ریپلائی آئٹم', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ کاروبار ━━━━━━━━━━
  {
    id: 'ecommerce-app',
    name: 'E-Commerce App',
    urduName: 'ای کامرس ایپ',
    description: 'Full e-commerce app with product listing, cart, checkout and order tracking',
    urduDescription: 'پروڈکٹ لسٹنگ، کارٹ، چیک آؤٹ اور آرڈر ٹریکنگ کے ساتھ مکمل ای کامرس',
    icon: 'store',
    color: '#ff9f43',
    category: 'کاروبار',
    isReady: true,
    tags: ['Shopping', 'Cart', 'Checkout'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/ProductListScreen.js', description: 'پروڈکٹ لسٹ', type: 'screen' },
      { path: 'screens/ProductDetailScreen.js', description: 'پروڈکٹ ڈیٹیل', type: 'screen' },
      { path: 'screens/CartScreen.js', description: 'کارٹ', type: 'screen' },
      { path: 'screens/CheckoutScreen.js', description: 'چیک آؤٹ', type: 'screen' },
      { path: 'screens/OrdersScreen.js', description: 'آرڈرز', type: 'screen' },
      { path: 'components/ProductCard.js', description: 'پروڈکٹ کارڈ', type: 'component' },
      { path: 'components/CartItem.js', description: 'کارٹ آئٹم', type: 'component' },
      { path: 'contexts/CartContext.js', description: 'کارٹ کانٹیکسٹ', type: 'context' },
      { path: 'data/products.js', description: 'پروڈکٹس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'restaurant-app',
    name: 'Restaurant Menu App',
    urduName: 'ریستوران ایپ',
    description: 'Restaurant menu with categories, order system, table booking',
    urduDescription: 'کیٹیگریز، آرڈر سسٹم، ٹیبل بکنگ کے ساتھ ریستوران مینو',
    icon: 'restaurant',
    color: '#e55039',
    category: 'کاروبار',
    isReady: true,
    tags: ['Food', 'Menu', 'Orders'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/MenuScreen.js', description: 'مینو', type: 'screen' },
      { path: 'screens/OrderScreen.js', description: 'آرڈر', type: 'screen' },
      { path: 'screens/TableScreen.js', description: 'ٹیبل', type: 'screen' },
      { path: 'components/MenuItem.js', description: 'مینو آئٹم', type: 'component' },
      { path: 'components/CategoryTabs.js', description: 'کیٹیگری ٹیبز', type: 'component' },
      { path: 'data/menu.js', description: 'مینو ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'pos-app',
    name: 'Point of Sale App',
    urduName: 'POS ایپ',
    description: 'Mobile point of sale with inventory, barcode scan, receipts and reports',
    urduDescription: 'انوینٹری، بارکوڈ اسکین، رسیدیں اور رپورٹس کے ساتھ موبائل POS',
    icon: 'point-of-sale',
    color: '#2ecc71',
    category: 'کاروبار',
    isReady: true,
    tags: ['POS', 'Sales', 'Inventory', 'Barcode'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/POSScreen.js', description: 'POS اسکرین', type: 'screen' },
      { path: 'screens/ProductsScreen.js', description: 'پروڈکٹس', type: 'screen' },
      { path: 'screens/ReceiptScreen.js', description: 'رسید', type: 'screen' },
      { path: 'screens/ReportsScreen.js', description: 'رپورٹس', type: 'screen' },
      { path: 'screens/InventoryScreen.js', description: 'انوینٹری', type: 'screen' },
      { path: 'components/ProductButton.js', description: 'پروڈکٹ بٹن', type: 'component' },
      { path: 'components/CartSummary.js', description: 'کارٹ خلاصہ', type: 'component' },
      { path: 'components/ReceiptPrint.js', description: 'رسید پرنٹ', type: 'component' },
      { path: 'contexts/POSContext.js', description: 'POS کانٹیکسٹ', type: 'context' },
      { path: 'services/barcodeService.js', description: 'بارکوڈ سروس', type: 'service' },
      { path: 'data/products.js', description: 'پروڈکٹس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'inventory-app',
    name: 'Inventory Manager',
    urduName: 'انوینٹری مینیجر',
    description: 'Stock management with items, categories, low stock alerts and reports',
    urduDescription: 'آئٹمز، کیٹیگریز، کم اسٹاک الرٹس اور رپورٹس کے ساتھ اسٹاک مینجمنٹ',
    icon: 'inventory-2',
    color: '#8e44ad',
    category: 'کاروبار',
    tags: ['Inventory', 'Stock', 'Alerts'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/StockScreen.js', description: 'اسٹاک', type: 'screen' },
      { path: 'screens/AddItemScreen.js', description: 'آئٹم شامل', type: 'screen' },
      { path: 'screens/AlertsScreen.js', description: 'الرٹس', type: 'screen' },
      { path: 'components/StockItem.js', description: 'اسٹاک آئٹم', type: 'component' },
      { path: 'components/StockChart.js', description: 'اسٹاک چارٹ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'food-delivery',
    name: 'Food Delivery App',
    urduName: 'فوڈ ڈیلیوری',
    description: 'Uber Eats-like food delivery with restaurants, menu and live tracking',
    urduDescription: 'ریستورانز، مینو اور لائیو ٹریکنگ کے ساتھ فوڈ ڈیلیوری ایپ',
    icon: 'delivery-dining',
    color: '#e74c3c',
    category: 'کاروبار',
    tags: ['Delivery', 'Food', 'Maps'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/RestaurantScreen.js', description: 'ریستوران', type: 'screen' },
      { path: 'screens/TrackingScreen.js', description: 'ٹریکنگ', type: 'screen' },
      { path: 'components/RestaurantCard.js', description: 'ریستوران کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'job-board',
    name: 'Job Board App',
    urduName: 'جاب بورڈ',
    description: 'Job listings with search, filters, apply and bookmark features',
    urduDescription: 'سرچ، فلٹرز، اپلائی اور بک مارک فیچرز کے ساتھ جاب لسٹنگز',
    icon: 'work',
    color: '#3498db',
    category: 'کاروبار',
    tags: ['Jobs', 'Search', 'Apply'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/JobListScreen.js', description: 'جاب لسٹ', type: 'screen' },
      { path: 'screens/JobDetailScreen.js', description: 'جاب ڈیٹیل', type: 'screen' },
      { path: 'components/JobCard.js', description: 'جاب کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'booking-app',
    name: 'Booking App',
    urduName: 'بکنگ ایپ',
    description: 'Appointment booking with calendar, time slots, confirmation and reminders',
    urduDescription: 'کیلنڈر، ٹائم سلاٹس، تصدیق اور ریمائنڈرز کے ساتھ اپائنٹمنٹ بکنگ',
    icon: 'event-available',
    color: '#8e44ad',
    category: 'کاروبار',
    tags: ['Booking', 'Calendar', 'Schedule'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/BookingScreen.js', description: 'بکنگ', type: 'screen' },
      { path: 'screens/ConfirmationScreen.js', description: 'تصدیق', type: 'screen' },
      { path: 'components/TimeSlotPicker.js', description: 'ٹائم سلاٹ پکر', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'digital-card',
    name: 'Digital Business Card',
    urduName: 'ڈیجیٹل بزنس کارڈ',
    description: 'Create and share digital business cards with QR code and contact import',
    urduDescription: 'QR کوڈ اور کانٹیکٹ امپورٹ کے ساتھ ڈیجیٹل بزنس کارڈ',
    icon: 'badge',
    color: '#2d3436',
    category: 'کاروبار',
    isReady: true,
    tags: ['Business Card', 'QR', 'Share'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CardScreen.js', description: 'کارڈ اسکرین', type: 'screen' },
      { path: 'screens/EditCardScreen.js', description: 'کارڈ ایڈٹ', type: 'screen' },
      { path: 'screens/ScanScreen.js', description: 'اسکین', type: 'screen' },
      { path: 'components/BusinessCard.js', description: 'بزنس کارڈ', type: 'component' },
      { path: 'components/QRDisplay.js', description: 'QR ڈسپلے', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'survey-app',
    name: 'Survey & Forms App',
    urduName: 'سروے ایپ',
    description: 'Build surveys with multiple question types, logic and analytics',
    urduDescription: 'متعدد سوال اقسام، منطق اور اینالٹکس کے ساتھ سروے بنائیں',
    icon: 'poll',
    color: '#0984e3',
    category: 'کاروبار',
    tags: ['Survey', 'Forms', 'Analytics'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/SurveysScreen.js', description: 'سروے لسٹ', type: 'screen' },
      { path: 'screens/TakeSurveyScreen.js', description: 'سروے دیں', type: 'screen' },
      { path: 'screens/ResultsScreen.js', description: 'نتائج', type: 'screen' },
      { path: 'components/QuestionCard.js', description: 'سوال کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ صحت ━━━━━━━━━━
  {
    id: 'fitness-tracker',
    name: 'Fitness Tracker',
    urduName: 'فٹنس ٹریکر',
    description: 'Workout logger with exercise library, sets/reps tracking and progress graphs',
    urduDescription: 'ورزش لائبریری، سیٹس/ریپس ٹریکنگ اور پروگریس گرافس',
    icon: 'fitness-center',
    color: '#e74c3c',
    category: 'صحت',
    tags: ['Fitness', 'Workout', 'Progress'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DashboardScreen.js', description: 'ڈیش بورڈ', type: 'screen' },
      { path: 'screens/WorkoutScreen.js', description: 'ورزش', type: 'screen' },
      { path: 'components/WorkoutCard.js', description: 'ورزش کارڈ', type: 'component' },
      { path: 'data/exercises.js', description: 'ورزشیں ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'diet-tracker',
    name: 'Diet & Nutrition App',
    urduName: 'غذا ٹریکر',
    description: 'Calorie counter with food database, meal planning and macros tracking',
    urduDescription: 'فوڈ ڈیٹا بیس، میل پلاننگ اور میکروز ٹریکنگ کے ساتھ کیلوری کاؤنٹر',
    icon: 'restaurant-menu',
    color: '#a8e063',
    category: 'صحت',
    tags: ['Diet', 'Calories', 'Nutrition'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DiaryScreen.js', description: 'ڈائری', type: 'screen' },
      { path: 'screens/SearchFoodScreen.js', description: 'فوڈ سرچ', type: 'screen' },
      { path: 'components/MealSection.js', description: 'میل سیکشن', type: 'component' },
      { path: 'data/foods.js', description: 'کھانے ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'meditation-app',
    name: 'Meditation App',
    urduName: 'مراقبہ ایپ',
    description: 'Guided meditation with ambient sounds, breathing exercises and tracking',
    urduDescription: 'محیط آوازیں، سانس مشقیں اور ٹریکنگ کے ساتھ مراقبہ',
    icon: 'self-improvement',
    color: '#81ecec',
    category: 'صحت',
    tags: ['Meditation', 'Breathing', 'Mindfulness'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/SessionScreen.js', description: 'سیشن', type: 'screen' },
      { path: 'components/BreathingCircle.js', description: 'سانس سرکل', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'water-tracker',
    name: 'Water Tracker',
    urduName: 'پانی ٹریکر',
    description: 'Daily water intake tracker with reminders, goals and hydration history',
    urduDescription: 'ریمائنڈرز، اہداف اور ہائیڈریشن ہسٹری کے ساتھ یومیہ پانی ٹریکر',
    icon: 'water-drop',
    color: '#74b9ff',
    category: 'صحت',
    tags: ['Water', 'Health', 'Reminders'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/WaterScreen.js', description: 'پانی اسکرین', type: 'screen' },
      { path: 'components/WaterGlass.js', description: 'پانی گلاس', type: 'component' },
      { path: 'components/ProgressRing.js', description: 'پروگریس رنگ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ تعلیم ━━━━━━━━━━
  {
    id: 'quiz-app',
    name: 'Quiz App',
    urduName: 'کوئز ایپ',
    description: 'Interactive quiz with multiple choice, timer, score tracking and leaderboard',
    urduDescription: 'ملٹیپل چوائس، ٹائمر، اسکور ٹریکنگ اور لیڈربورڈ',
    icon: 'quiz',
    color: '#a29bfe',
    category: 'تعلیم',
    isReady: true,
    tags: ['Quiz', 'Timer', 'Score'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/QuizScreen.js', description: 'کوئز', type: 'screen' },
      { path: 'screens/ResultsScreen.js', description: 'نتائج', type: 'screen' },
      { path: 'components/QuestionCard.js', description: 'سوال کارڈ', type: 'component' },
      { path: 'data/questions.js', description: 'سوالات ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'flashcard-app',
    name: 'Flashcard App',
    urduName: 'فلیش کارڈ',
    description: 'Spaced repetition flashcards with decks, flip animations and progress',
    urduDescription: 'ڈیکس، فلپ انیمیشنز اور پروگریس کے ساتھ فلیش کارڈز',
    icon: 'style',
    color: '#ffeaa7',
    category: 'تعلیم',
    tags: ['Flashcards', 'Learning', 'Animation'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DecksScreen.js', description: 'ڈیکس', type: 'screen' },
      { path: 'screens/StudyScreen.js', description: 'مطالعہ', type: 'screen' },
      { path: 'components/FlipCard.js', description: 'فلپ کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'language-learning',
    name: 'Language Learning App',
    urduName: 'زبان سیکھیں',
    description: 'Duolingo-like language app with lessons, exercises and streak system',
    urduDescription: 'سبق، مشقیں اور اسٹریک سسٹم کے ساتھ زبان سیکھنے کی ایپ',
    icon: 'translate',
    color: '#55efc4',
    category: 'تعلیم',
    isReady: true,
    tags: ['Language', 'Lessons', 'Streak'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/LessonScreen.js', description: 'سبق', type: 'screen' },
      { path: 'components/ProgressPath.js', description: 'پروگریس پاتھ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'course-app',
    name: 'Online Course App',
    urduName: 'آن لائن کورس',
    description: 'Course player with video lessons, quizzes, certificates and progress',
    urduDescription: 'ویڈیو سبق، کوئزز، سرٹیفکیٹس اور پروگریس کے ساتھ کورس پلیئر',
    icon: 'school',
    color: '#0984e3',
    category: 'تعلیم',
    tags: ['Courses', 'Video', 'Certificate'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CoursesScreen.js', description: 'کورسز', type: 'screen' },
      { path: 'screens/LessonPlayerScreen.js', description: 'سبق پلیئر', type: 'screen' },
      { path: 'components/CourseCard.js', description: 'کورس کارڈ', type: 'component' },
      { path: 'data/courses.js', description: 'کورسز ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ مالیات ━━━━━━━━━━
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    urduName: 'خرچہ ٹریکر',
    description: 'Budget tracker with categories, charts, recurring expenses and export',
    urduDescription: 'کیٹیگریز، چارٹس، بار بار خرچے اور ایکسپورٹ کے ساتھ بجٹ ٹریکر',
    icon: 'account-balance-wallet',
    color: '#00b894',
    category: 'مالیات',
    isReady: true,
    tags: ['Budget', 'Charts', 'Finance'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DashboardScreen.js', description: 'ڈیش بورڈ', type: 'screen' },
      { path: 'screens/TransactionsScreen.js', description: 'ٹرانزیکشنز', type: 'screen' },
      { path: 'components/TransactionItem.js', description: 'ٹرانزیکشن آئٹم', type: 'component' },
      { path: 'components/PieChart.js', description: 'پائی چارٹ', type: 'component' },
      { path: 'contexts/ExpenseContext.js', description: 'خرچہ کانٹیکسٹ', type: 'context' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'crypto-tracker',
    name: 'Crypto Tracker',
    urduName: 'کرپٹو ٹریکر',
    description: 'Cryptocurrency tracker with live prices, portfolio and price alerts',
    urduDescription: 'لائیو قیمتیں، پورٹ فولیو اور قیمت الرٹس کے ساتھ کرپٹو ٹریکر',
    icon: 'currency-bitcoin',
    color: '#f9ca24',
    category: 'مالیات',
    tags: ['Crypto', 'Portfolio', 'Charts'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/MarketScreen.js', description: 'مارکیٹ', type: 'screen' },
      { path: 'screens/PortfolioScreen.js', description: 'پورٹ فولیو', type: 'screen' },
      { path: 'components/CoinCard.js', description: 'کوائن کارڈ', type: 'component' },
      { path: 'services/cryptoAPI.js', description: 'کرپٹو API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'banking-app',
    name: 'Banking App UI',
    urduName: 'بینکنگ ایپ',
    description: 'Modern banking UI with accounts, transfers, transactions and card management',
    urduDescription: 'اکاؤنٹس، ٹرانسفرز، ٹرانزیکشنز اور کارڈ مینجمنٹ',
    icon: 'account-balance',
    color: '#2d3436',
    category: 'مالیات',
    tags: ['Banking', 'Cards', 'Transfer'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/TransferScreen.js', description: 'ٹرانسفر', type: 'screen' },
      { path: 'components/BalanceCard.js', description: 'بیلنس کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ سفر ━━━━━━━━━━
  {
    id: 'weather-app',
    name: 'Weather App',
    urduName: 'موسم ایپ',
    description: 'Weather app with hourly/weekly forecast, maps and weather alerts',
    urduDescription: 'گھنٹہ وار/ہفتہ وار پیش گوئی، میپس اور موسمی الرٹس',
    icon: 'wb-sunny',
    color: '#f39c12',
    category: 'سفر',
    isReady: true,
    tags: ['Weather', 'Forecast', 'API'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/WeatherScreen.js', description: 'موسم', type: 'screen' },
      { path: 'components/WeatherCard.js', description: 'موسم کارڈ', type: 'component' },
      { path: 'services/weatherAPI.js', description: 'موسم API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'travel-guide',
    name: 'Travel Guide App',
    urduName: 'ٹریول گائیڈ',
    description: 'Travel app with destinations, itineraries, tips and offline maps',
    urduDescription: 'منزلیں، سفر نامے، ٹپس اور آف لائن میپس',
    icon: 'flight',
    color: '#3498db',
    category: 'سفر',
    tags: ['Travel', 'Maps', 'Itinerary'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DestinationScreen.js', description: 'منزل', type: 'screen' },
      { path: 'components/DestinationCard.js', description: 'منزل کارڈ', type: 'component' },
      { path: 'data/destinations.js', description: 'منزلیں ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'maps-app',
    name: 'Maps & Navigation',
    urduName: 'نقشہ جات',
    description: 'Location app with maps, directions, POIs and real-time tracking',
    urduDescription: 'نقشے، سمت، دلچسپ مقامات اور ریئل ٹائم ٹریکنگ',
    icon: 'map',
    color: '#27ae60',
    category: 'سفر',
    tags: ['Maps', 'GPS', 'Navigation'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/MapScreen.js', description: 'نقشہ', type: 'screen' },
      { path: 'components/MapView.js', description: 'میپ ویو', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ ڈیش بورڈ ━━━━━━━━━━
  {
    id: 'dashboard-app',
    name: 'Dashboard App',
    urduName: 'ڈیش بورڈ ایپ',
    description: 'Analytics dashboard with stats cards, bar/line charts and data tables',
    urduDescription: 'اسٹیٹس کارڈز، بار/لائن چارٹس اور ڈیٹا ٹیبلز',
    icon: 'dashboard',
    color: '#2ecc71',
    category: 'ڈیش بورڈ',
    isReady: true,
    tags: ['Charts', 'Analytics', 'Data'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DashboardScreen.js', description: 'ڈیش بورڈ', type: 'screen' },
      { path: 'components/StatsCard.js', description: 'اسٹیٹس کارڈ', type: 'component' },
      { path: 'components/BarChart.js', description: 'بار چارٹ', type: 'component' },
      { path: 'components/DataTable.js', description: 'ڈیٹا ٹیبل', type: 'component' },
      { path: 'data/analytics.js', description: 'اینالٹکس ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'admin-panel',
    name: 'Admin Panel',
    urduName: 'ایڈمن پینل',
    description: 'Mobile admin panel with user management, reports and settings',
    urduDescription: 'یوزر مینجمنٹ، رپورٹس اور سیٹنگز کے ساتھ موبائل ایڈمن پینل',
    icon: 'admin-panel-settings',
    color: '#e74c3c',
    category: 'ڈیش بورڈ',
    tags: ['Admin', 'Management', 'Reports'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/AdminHomeScreen.js', description: 'ایڈمن ہوم', type: 'screen' },
      { path: 'screens/UsersScreen.js', description: 'یوزرز', type: 'screen' },
      { path: 'components/UserRow.js', description: 'یوزر رو', type: 'component' },
      { path: 'components/MetricCard.js', description: 'میٹرک کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'crm-app',
    name: 'CRM App',
    urduName: 'CRM ایپ',
    description: 'Customer relationship manager with contacts, deals pipeline and tasks',
    urduDescription: 'کانٹیکٹس، ڈیلز پائپ لائن اور ٹاسکس کے ساتھ CRM',
    icon: 'people',
    color: '#8e44ad',
    category: 'ڈیش بورڈ',
    tags: ['CRM', 'Contacts', 'Pipeline'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ContactsScreen.js', description: 'کانٹیکٹس', type: 'screen' },
      { path: 'screens/DealsScreen.js', description: 'ڈیلز', type: 'screen' },
      { path: 'components/DealCard.js', description: 'ڈیل کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ یوٹیلیٹی ━━━━━━━━━━
  {
    id: 'keyboard-app',
    name: 'Keyboard App',
    urduName: 'کی بورڈ ایپ',
    description: 'Custom keyboard with multiple layouts and vibration feedback',
    urduDescription: 'متعدد لے آؤٹس اور وائبریشن کے ساتھ کسٹم کی بورڈ',
    icon: 'keyboard',
    color: '#ffd700',
    category: 'یوٹیلیٹی',
    tags: ['Input', 'Vibration', 'Custom UI'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/KeyboardSetup.js', description: 'کی بورڈ سیٹ اپ', type: 'screen' },
      { path: 'components/KeyButton.js', description: 'کی بٹن', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'browser-app',
    name: 'Browser App',
    urduName: 'براؤزر ایپ',
    description: 'Full-featured web browser with history, bookmarks and tabs',
    urduDescription: 'ہسٹری، بک مارکس اور ٹیبز کے ساتھ مکمل ویب براؤزر',
    icon: 'language',
    color: '#61dafb',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['WebView', 'History', 'Bookmarks'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/BrowserScreen.js', description: 'براؤزر اسکرین', type: 'screen' },
      { path: 'screens/BookmarksScreen.js', description: 'بک مارکس', type: 'screen' },
      { path: 'components/AddressBar.js', description: 'ایڈریس بار', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'basic-app',
    name: 'Basic App',
    urduName: 'بنیادی ایپ',
    description: 'Simple starter app with navigation, state management and basic components',
    urduDescription: 'نیویگیشن، اسٹیٹ مینجمنٹ اور بنیادی کمپوننٹس کے ساتھ سادہ ایپ',
    icon: 'phone-android',
    color: '#a8ff78',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['Starter', 'Navigation', 'State'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم اسکرین', type: 'screen' },
      { path: 'components/Card.js', description: 'کارڈ کمپوننٹ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'qr-scanner',
    name: 'QR Scanner App',
    urduName: 'QR اسکینر',
    description: 'QR and barcode scanner with history, generator and sharing',
    urduDescription: 'ہسٹری، جنریٹر اور شیئرنگ کے ساتھ QR اسکینر',
    icon: 'qr-code-scanner',
    color: '#00cec9',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['QR', 'Camera', 'Scanner'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ScannerScreen.js', description: 'اسکینر', type: 'screen' },
      { path: 'screens/GeneratorScreen.js', description: 'جنریٹر', type: 'screen' },
      { path: 'components/ScannerOverlay.js', description: 'اسکینر اوورلے', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'news-app',
    name: 'News App',
    urduName: 'خبریں ایپ',
    description: 'News reader with categories, bookmarks, offline reading and sharing',
    urduDescription: 'کیٹیگریز، بک مارکس، آف لائن ریڈنگ اور شیئرنگ',
    icon: 'article',
    color: '#d63031',
    category: 'یوٹیلیٹی',
    tags: ['News', 'Feed', 'Articles'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/NewsListScreen.js', description: 'خبریں لسٹ', type: 'screen' },
      { path: 'screens/ArticleScreen.js', description: 'مضمون', type: 'screen' },
      { path: 'components/NewsCard.js', description: 'خبریں کارڈ', type: 'component' },
      { path: 'services/newsAPI.js', description: 'خبریں API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'recipe-app',
    name: 'Recipe App',
    urduName: 'ترکیب ایپ',
    description: 'Recipe app with ingredients, step-by-step instructions and timers',
    urduDescription: 'اجزاء، مرحلہ وار ہدایات اور ٹائمرز کے ساتھ ترکیب ایپ',
    icon: 'soup-kitchen',
    color: '#e17055',
    category: 'یوٹیلیٹی',
    tags: ['Recipes', 'Cooking', 'Timer'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/RecipesScreen.js', description: 'ترکیبیں', type: 'screen' },
      { path: 'screens/RecipeDetailScreen.js', description: 'ترکیب ڈیٹیل', type: 'screen' },
      { path: 'components/RecipeCard.js', description: 'ترکیب کارڈ', type: 'component' },
      { path: 'data/recipes.js', description: 'ترکیبیں ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'voice-recorder',
    name: 'Voice Recorder App',
    urduName: 'وائس ریکارڈر',
    description: 'Record, playback, trim and share voice notes with categories',
    urduDescription: 'کیٹیگریز کے ساتھ وائس نوٹس ریکارڈ، پلے بیک، ٹرم اور شیئر',
    icon: 'mic',
    color: '#e74c3c',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['Audio', 'Record', 'expo-av'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/RecorderScreen.js', description: 'ریکارڈر', type: 'screen' },
      { path: 'screens/RecordingsScreen.js', description: 'ریکارڈنگز', type: 'screen' },
      { path: 'components/WaveForm.js', description: 'ویو فارم', type: 'component' },
      { path: 'components/RecordingItem.js', description: 'ریکارڈنگ آئٹم', type: 'component' },
      { path: 'hooks/useRecorder.js', description: 'ریکارڈر ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'document-scanner',
    name: 'Document Scanner',
    urduName: 'ڈاکومنٹ اسکینر',
    description: 'Scan documents with camera, crop, enhance and export as PDF',
    urduDescription: 'کیمرا سے اسکین، کراپ، انہانس اور PDF ایکسپورٹ',
    icon: 'document-scanner',
    color: '#0984e3',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['Scanner', 'PDF', 'Camera'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ScannerScreen.js', description: 'اسکینر', type: 'screen' },
      { path: 'screens/DocumentsScreen.js', description: 'ڈاکومنٹس', type: 'screen' },
      { path: 'screens/EditScreen.js', description: 'ایڈیٹ', type: 'screen' },
      { path: 'components/CameraView.js', description: 'کیمرا ویو', type: 'component' },
      { path: 'components/DocumentCard.js', description: 'ڈاکومنٹ کارڈ', type: 'component' },
      { path: 'utils/pdfExport.js', description: 'PDF ایکسپورٹ', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    urduName: 'کرنسی کنورٹر',
    description: 'Real-time currency conversion with 170+ currencies and offline support',
    urduDescription: '170+ کرنسیز اور آف لائن سپورٹ کے ساتھ ریئل ٹائم کرنسی کنورژن',
    icon: 'currency-exchange',
    color: '#f9ca24',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['Currency', 'Forex', 'Rates'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/ConverterScreen.js', description: 'کنورٹر', type: 'screen' },
      { path: 'screens/RatesScreen.js', description: 'ریٹس', type: 'screen' },
      { path: 'components/CurrencyPicker.js', description: 'کرنسی پکر', type: 'component' },
      { path: 'services/exchangeAPI.js', description: 'ایکسچینج API', type: 'service' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'alarm-clock',
    name: 'Alarm Clock App',
    urduName: 'الارم گھڑی',
    description: 'Smart alarm with snooze, multiple alarms, sleep timer and ringtones',
    urduDescription: 'اسنوز، متعدد الارمز، سلیپ ٹائمر اور رنگ ٹونز',
    icon: 'alarm',
    color: '#6c5ce7',
    category: 'یوٹیلیٹی',
    isReady: true,
    tags: ['Alarm', 'Timer', 'Notifications'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/AlarmsScreen.js', description: 'الارمز', type: 'screen' },
      { path: 'screens/AddAlarmScreen.js', description: 'الارم شامل', type: 'screen' },
      { path: 'components/AlarmCard.js', description: 'الارم کارڈ', type: 'component' },
      { path: 'components/TimePicker.js', description: 'ٹائم پکر', type: 'component' },
      { path: 'hooks/useAlarm.js', description: 'الارم ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ گیمز ━━━━━━━━━━
  {
    id: 'word-game',
    name: 'Word Game (Wordle)',
    urduName: 'لفظ گیم',
    description: 'Wordle-inspired word guessing game with keyboard, hints and daily challenges',
    urduDescription: 'کی بورڈ، ہنٹس اور روزانہ چیلنجز کے ساتھ Wordle جیسا لفظ گیم',
    icon: 'spellcheck',
    color: '#2ecc71',
    category: 'گیمز',
    isReady: true,
    tags: ['Game', 'Words', 'Puzzle'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/GameScreen.js', description: 'گیم', type: 'screen' },
      { path: 'screens/ResultScreen.js', description: 'نتیجہ', type: 'screen' },
      { path: 'screens/StatsScreen.js', description: 'اسٹیٹس', type: 'screen' },
      { path: 'components/WordGrid.js', description: 'لفظ گرڈ', type: 'component' },
      { path: 'components/KeyboardView.js', description: 'کی بورڈ ویو', type: 'component' },
      { path: 'components/LetterTile.js', description: 'حرف ٹائل', type: 'component' },
      { path: 'data/words.js', description: 'الفاظ ڈیٹا', type: 'data' },
      { path: 'hooks/useWordGame.js', description: 'گیم ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'trivia-game',
    name: 'Trivia Game App',
    urduName: 'ٹریویا گیم',
    description: 'Multiplayer trivia game with categories, lifelines, timer and leaderboard',
    urduDescription: 'کیٹیگریز، لائف لائنز، ٹائمر اور لیڈربورڈ کے ساتھ ٹریویا گیم',
    icon: 'emoji-events',
    color: '#f9ca24',
    category: 'گیمز',
    tags: ['Trivia', 'Quiz', 'Multiplayer'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/MenuScreen.js', description: 'مینو', type: 'screen' },
      { path: 'screens/GameScreen.js', description: 'گیم', type: 'screen' },
      { path: 'screens/LeaderboardScreen.js', description: 'لیڈربورڈ', type: 'screen' },
      { path: 'components/AnswerButton.js', description: 'جواب بٹن', type: 'component' },
      { path: 'components/LifeLines.js', description: 'لائف لائنز', type: 'component' },
      { path: 'data/questions.js', description: 'سوالات', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'chess-app',
    name: 'Chess Game App',
    urduName: 'شطرنج',
    description: 'Chess game with AI opponent, move history, analysis and puzzles',
    urduDescription: 'AI مخالف، چال ہسٹری، تجزیہ اور پہیلیوں کے ساتھ شطرنج',
    icon: 'sports-esports',
    color: '#dfe6e9',
    category: 'گیمز',
    tags: ['Chess', 'AI', 'Strategy'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/GameScreen.js', description: 'گیم', type: 'screen' },
      { path: 'screens/PuzzlesScreen.js', description: 'پہیلیاں', type: 'screen' },
      { path: 'components/ChessBoard.js', description: 'شطرنج بورڈ', type: 'component' },
      { path: 'components/ChessPiece.js', description: 'مہرہ', type: 'component' },
      { path: 'utils/chessEngine.js', description: 'شطرنج انجن', type: 'util' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'puzzle-app',
    name: 'Puzzle Game App',
    urduName: 'پہیلی گیم',
    description: 'Jigsaw and number puzzles with difficulty levels and completion tracking',
    urduDescription: 'مشکل کی سطحیں اور مکمل ٹریکنگ کے ساتھ پہیلی گیم',
    icon: 'extension',
    color: '#a29bfe',
    category: 'گیمز',
    tags: ['Puzzle', 'Jigsaw', 'Numbers'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/PuzzleMenuScreen.js', description: 'پہیلی مینو', type: 'screen' },
      { path: 'screens/JigsawScreen.js', description: 'جگ سا', type: 'screen' },
      { path: 'screens/NumberScreen.js', description: 'نمبر پہیلی', type: 'screen' },
      { path: 'components/PuzzleGrid.js', description: 'پہیلی گرڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'drawing-app',
    name: 'Drawing & Doodle App',
    urduName: 'ڈرائنگ ایپ',
    description: 'Canvas drawing app with brushes, colors, layers, undo and share',
    urduDescription: 'برشز، رنگ، تہیں، انڈو اور شیئر کے ساتھ کینوس ڈرائنگ',
    icon: 'brush',
    color: '#00b894',
    category: 'گیمز',
    isReady: true,
    tags: ['Drawing', 'Canvas', 'Creative'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/CanvasScreen.js', description: 'کینوس', type: 'screen' },
      { path: 'screens/GalleryScreen.js', description: 'گیلری', type: 'screen' },
      { path: 'components/DrawingCanvas.js', description: 'ڈرائنگ کینوس', type: 'component' },
      { path: 'components/ColorPicker.js', description: 'رنگ پکر', type: 'component' },
      { path: 'components/BrushSelector.js', description: 'برش سلیکٹر', type: 'component' },
      { path: 'components/ToolBar.js', description: 'ٹول بار', type: 'component' },
      { path: 'hooks/useCanvas.js', description: 'کینوس ہک', type: 'hook' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'card-game',
    name: 'Card Game App',
    urduName: 'کارڈ گیم',
    description: 'Classic card games: Solitaire, War, Memory Match with animations',
    urduDescription: 'کلاسک کارڈ گیمز: سولیٹیئر، وار، میموری میچ انیمیشنز کے ساتھ',
    icon: 'casino',
    color: '#e17055',
    category: 'گیمز',
    tags: ['Cards', 'Solitaire', 'Animation'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/GameSelectScreen.js', description: 'گیم سلیکٹ', type: 'screen' },
      { path: 'screens/SolitaireScreen.js', description: 'سولیٹیئر', type: 'screen' },
      { path: 'screens/MemoryScreen.js', description: 'میموری میچ', type: 'screen' },
      { path: 'components/PlayingCard.js', description: 'کارڈ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },

  // ━━━━━━━━━━ فیملی ━━━━━━━━━━
  {
    id: 'kids-learning',
    name: 'Kids Learning App',
    urduName: 'بچوں کی تعلیم',
    description: 'Fun learning for kids: ABCs, numbers, shapes, colors and animals',
    urduDescription: 'بچوں کے لیے تفریحی تعلیم: حروف، نمبرز، اشکال، رنگ اور جانور',
    icon: 'child-care',
    color: '#fdcb6e',
    category: 'فیملی',
    isReady: true,
    tags: ['Kids', 'Learning', 'Animations'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/HomeScreen.js', description: 'ہوم', type: 'screen' },
      { path: 'screens/ABCScreen.js', description: 'حروف تہجی', type: 'screen' },
      { path: 'screens/NumbersScreen.js', description: 'نمبرز', type: 'screen' },
      { path: 'screens/AnimalsScreen.js', description: 'جانور', type: 'screen' },
      { path: 'screens/ColorsScreen.js', description: 'رنگ', type: 'screen' },
      { path: 'components/LessonCard.js', description: 'سبق کارڈ', type: 'component' },
      { path: 'components/AnimatedCharacter.js', description: 'متحرک کردار', type: 'component' },
      { path: 'data/lessons.js', description: 'اسباق ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'family-organizer',
    name: 'Family Organizer App',
    urduName: 'فیملی آرگنائزر',
    description: 'Shared family calendar, chores list, shopping and family chat',
    urduDescription: 'مشترکہ فیملی کیلنڈر، کام لسٹ، شاپنگ اور فیملی چیٹ',
    icon: 'family-restroom',
    color: '#74b9ff',
    category: 'فیملی',
    isReady: true,
    tags: ['Family', 'Calendar', 'Chores'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/FamilyHomeScreen.js', description: 'فیملی ہوم', type: 'screen' },
      { path: 'screens/CalendarScreen.js', description: 'کیلنڈر', type: 'screen' },
      { path: 'screens/ChoresScreen.js', description: 'گھر کے کام', type: 'screen' },
      { path: 'screens/ShoppingScreen.js', description: 'شاپنگ', type: 'screen' },
      { path: 'screens/ChatScreen.js', description: 'فیملی چیٹ', type: 'screen' },
      { path: 'components/MemberAvatar.js', description: 'فیملی ممبر', type: 'component' },
      { path: 'components/ChoreItem.js', description: 'کام آئٹم', type: 'component' },
      { path: 'contexts/FamilyContext.js', description: 'فیملی کانٹیکسٹ', type: 'context' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'baby-tracker',
    name: 'Baby Tracker App',
    urduName: 'بچے کا ٹریکر',
    description: 'Track baby feeding, sleep, diaper changes, growth and milestones',
    urduDescription: 'دودھ پلانا، نیند، ڈائپر تبدیلی، نشوونما اور سنگ میل',
    icon: 'baby-changing-station',
    color: '#fd79a8',
    category: 'فیملی',
    isReady: true,
    tags: ['Baby', 'Parenting', 'Health'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/DashboardScreen.js', description: 'ڈیش بورڈ', type: 'screen' },
      { path: 'screens/FeedingScreen.js', description: 'دودھ پلانا', type: 'screen' },
      { path: 'screens/SleepScreen.js', description: 'نیند', type: 'screen' },
      { path: 'screens/GrowthScreen.js', description: 'نشوونما', type: 'screen' },
      { path: 'screens/MilestonesScreen.js', description: 'سنگ میل', type: 'screen' },
      { path: 'components/ActivityLog.js', description: 'ایکٹیویٹی لاگ', type: 'component' },
      { path: 'components/GrowthChart.js', description: 'نشوونما چارٹ', type: 'component' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'coloring-app',
    name: 'Coloring Book App',
    urduName: 'رنگ بھرنے کی کتاب',
    description: 'Kids coloring app with pre-drawn outlines, color palette and save',
    urduDescription: 'پہلے سے بنی تصاویر، رنگ پیلیٹ اور محفوظ کرنے کے ساتھ رنگ بھرنا',
    icon: 'color-lens',
    color: '#a29bfe',
    category: 'فیملی',
    tags: ['Coloring', 'Kids', 'Creative'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/BookScreen.js', description: 'کتاب', type: 'screen' },
      { path: 'screens/ColoringScreen.js', description: 'رنگ بھرنا', type: 'screen' },
      { path: 'components/ColoringCanvas.js', description: 'رنگ کینوس', type: 'component' },
      { path: 'components/PaletteBar.js', description: 'رنگ پیلیٹ', type: 'component' },
      { path: 'data/outlines.js', description: 'تصاویر ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
  {
    id: 'bedtime-stories',
    name: 'Bedtime Stories App',
    urduName: 'رات کی کہانیاں',
    description: 'Audio bedtime stories for kids with sleep sounds, narration and timer',
    urduDescription: 'نیند کی آوازیں، بیان اور ٹائمر کے ساتھ بچوں کی آڈیو کہانیاں',
    icon: 'nightlight',
    color: '#6c5ce7',
    category: 'فیملی',
    tags: ['Stories', 'Kids', 'Audio', 'Sleep'],
    files: [
      { path: 'App.js', description: 'مین ایپ', type: 'component' },
      { path: 'screens/StoriesListScreen.js', description: 'کہانیاں لسٹ', type: 'screen' },
      { path: 'screens/StoryPlayerScreen.js', description: 'کہانی پلیئر', type: 'screen' },
      { path: 'components/StoryCard.js', description: 'کہانی کارڈ', type: 'component' },
      { path: 'components/SleepTimer.js', description: 'نیند ٹائمر', type: 'component' },
      { path: 'data/stories.js', description: 'کہانیاں ڈیٹا', type: 'data' },
      { path: 'package.json', description: 'ڈیپنڈینسیز', type: 'config' },
    ],
  },
];

export const HTML_CONVERSION_RULES = [
  { html: '<div>', rn: '<View>', color: '#61dafb' },
  { html: '<section>', rn: '<View>', color: '#61dafb' },
  { html: '<p>', rn: '<Text>', color: '#a8ff78' },
  { html: '<span>', rn: '<Text>', color: '#a8ff78' },
  { html: '<h1>–<h6>', rn: '<Text style={{fontWeight}}>', color: '#a8ff78' },
  { html: '<img>', rn: '<Image>', color: '#ff6b6b' },
  { html: '<button>', rn: '<TouchableOpacity>', color: '#ffd700' },
  { html: '<input>', rn: '<TextInput>', color: '#ff9f43' },
  { html: '<textarea>', rn: '<TextInput multiline>', color: '#ff9f43' },
  { html: '<a href>', rn: '<Pressable>', color: '#ffd700' },
  { html: '<ul>/<ol>', rn: '<View>', color: '#61dafb' },
  { html: '<li>', rn: '<View> (FlatList item)', color: '#a29bfe' },
  { html: '<form>', rn: '<View>', color: '#61dafb' },
  { html: '<table>', rn: '<View>', color: '#61dafb' },
  { html: '<strong>', rn: '<Text fontWeight bold>', color: '#a8ff78' },
  { html: '<em>', rn: '<Text fontStyle italic>', color: '#a8ff78' },
  { html: '<hr>', rn: '<View borderBottom>', color: '#b2bec3' },
  { html: '<br>', rn: '{/* newline */}', color: '#b2bec3' },
  { html: '<select>', rn: '<Picker>', color: '#fdcb6e' },
  { html: '<video>', rn: '<Video (expo-video)>', color: '#ff6b6b' },
];
